import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThirdwebProviderWrapper from "./ThirdwebProvider";
import "./globals.css";
import Header from "../components/ui/Header";
import { AppUIProvider } from "../components/ui/AppUIContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Only for client components, but for now, just render children
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThirdwebProviderWrapper>
          <AppUIProvider>
            <Header />
            {children}
          </AppUIProvider>
        </ThirdwebProviderWrapper>
      </body>
    </html>
  );
}
