[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# RPC URLs - Etherlink configuration
[rpc_endpoints]
etherlink = "https://node.ghostnet.etherlink.com"
etherlink_testnet = "https://node.ghostnet.etherlink.com"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# Etherscan configuration for verification
[etherscan]
etherlink = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet-explorer.etherlink.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
